services:
  influxdb:
    image: influxdb:2.9.1
    container_name: influxdb
    ports:
      - "8087:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb
      DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
      DOCKER_INFLUXDB_INIT_ORG: trabalho-nosql-org
      DOCKER_INFLUXDB_INIT_BUCKET: trabalho-nosql
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token_influx
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data: